### ISSUE TITLE
Emoji not working on windows

### ISSUE THREAD

**Issue by akinolu52** [ealush/emoji-picker-react#105]
Hello @all, thanks for the nice package, this package works perfectly on mac os & iOS but it's not working on a windows system, Any help?

**Comment by ealush** [comment]
Hey @akinolu52, sorry that you're experiencing trouble with the package. I just tested the latest version of the picker with IE11 on windows 10 and it seems to work without a problem.

![image](https://user-images.githubusercontent.com/11255103/60728810-e7afd500-9f49-11e9-943e-84b0888b8509.png)


Can you elaborate on the conditions in which you tested the component? Your OS, browser, package version, environment (Create react app, storybook, custom built react app), and what exactly doesn't work (does it not load at all, or do some of the features still exist?).
