### ISSUE TITLE
Is there a way to add a default diversity-picker value?

### ISSUE THREAD

**Issue by xanderjakeq** [ealush/emoji-picker-react#125]

**Comment by ealush** [comment]
Hey @xanderjakeq, no, at the moment it is not possible, but it shouldn't be hard to add. I am on vacation at the moment, but please, feel free to issue a PR for this feature.

All you need to do, is add another property to EmojiPicker which sets the initial `activeModifier` to something other than `null` on this line: https://github.com/ealush/emoji-picker-react/blob/master/src/EmojiPicker/index.js#L22

**Comment by ealush** [comment]
Hey @xanderjakeq, last night I published `emoji-picker-react@3.0.0`. This version supports [setting a default skin tone modifier](https://github.com/ealush/emoji-picker-react#setting-a-default-skin-tone-modifier). Let me know if that works for you.
