### ISSUE TITLE
Why UNLICENSED?

### ISSUE THREAD

**Issue by w01fgang** [ealush/emoji-picker-react#132]
I wanted to use this fantastic picker in my project, but I can't because of the license.
There is any reason to be unlicensed?

**Comment by ealush** [comment]
Hey, I believe you are right. I used UNLICENSED in initial development stage, planning to change it to [the unlicense](https://en.wikipedia.org/wiki/Unlicense), which is what I am going to do now.

**Comment by ealush** [comment]
@w01fgang, Done.
I pushed a new version, 3.1.0, with `The Unlicense`, which basically prevents you to do anything with the package, without any restrictions. I hope it is not too late for you to use the package.

**Comment by w01fgang** [comment]
@ealush you were on time, thank you! :D
