### ISSUE TITLE
Duplicated emoji

### ISSUE THREAD

**Issue by GruFFix** [ealush/emoji-picker-react#135]
Some of the smiles are duplicated. Is this a bug or a feature?

**Comment by ealush** [comment]
The list of all emojis comes from https://github.com/iamcal/emoji-data, I then parse the list and produce what we use in the picker.
There may be a bug in the parsing&transformation phase, or in the datasource. Can you please let me know which emojis you see repeating so I can investigate this?

**Comment by prak281993** [comment]
const emojiArr=[...emojis];
        setChosenEmoji(emojiObject.emoji);
        const text=`${postText} ${emojiObject.emoji}`;
        setPostText(text);

         postText is a state property which is set on typing in input field but it is null inside the callback function of onEmojiClick.

**Comment by prak281993** [comment]
Inside the onEmojiClick handler I am trying to append the chosen emoji icon with my postText state. But the value of all the state properties are null inside the onEmojiClick handler.
