### ISSUE TITLE
Reduce Icons By Default

### ISSUE THREAD

**Issue by Igcorreia** [ealush/emoji-picker-react#141]
We tried to use the picker but we noticed that the default config is 160px for an emoji picker is too much.

We suggest to use a 16px or 32pxso the file size is reduced onload. That can be the reason why performance is affected.

**Comment by ealush** [comment]
Hey @Igcorreia, I don't host the emojis myself, but feel free to do so. The picker accepts a prop called `emojiUrl`, and it is currently set to the 160px version of the emojis.

You can pass to your picker:
`<Picker emojiUrl="https://cdn.jsdelivr.net/gh/iamcal/emoji-data@master/img-apple-64"/>` which will use 64px images. I don't have a source for 32px or 16px images though.

**Comment by ealush** [comment]
I reduced the default image size to 64px.
