### ISSUE TITLE
components unmount warning

### ISSUE THREAD

**Issue by ximanWang** [ealush/emoji-picker-react#142]
I know that Loading the Picker needs some time, but if the component unmount during the Picker rendering, I will see this warning in broswer console. Is there any way that I can do when the component is unmount ?
![image](https://user-images.githubusercontent.com/13268272/75128200-21229400-5717-11ea-9974-41ff9bfd7a48.png)

**Comment by ealush** [comment]
Hey @ximanWang, since the picker is quite a heavy component, I would recommend not to unmount it every time you want to hide it, but instead set its display to none.

Other than that, in which stage do you exactly experience this? Can you please send a screen recording or a way to repro?

**Comment by ximanWang** [comment]
Hi @ealush , thanks for replying. Currently I have a chat system and I use this emoji package to allow client send emoji when chatting which is really nice. Each time when client open a channel the Channel components (Picker is inside the Channel) will render, when the client go back to channel list, the Channel component will unmount. So If the client switch between channel and list frequently, this warning will appear. Hope my explaination can make sence. 
Since you don't recommend to unmount it every time, I can initialize the Picker in my channel list page not in channel, may be this is a good way.

**Comment by ealush** [comment]
Hm. Now that I look at your screenshot again, it looks like the error is not actually coming from the Emoji Picker itself, but from some other component called `EmojiSelector` which is not a part of this package.

I tested rapidly mounting and unmounting the picker and it didn't throw the error. Can you double check to see if it is indeed the Emoji Picker that's causing the errors on your end or something else?

**Comment by ximanWang** [comment]
I use yarn dev mode (not build js) can see this warning, were you using dev mode for testing? My EmojiSelector compoonent only include Picker, and the warning said in **yf** (created by EmojiSelector), and I use React dev tools can see this **yf** is in Picker.
![image](https://user-images.githubusercontent.com/13268272/75297265-7b406800-5883-11ea-96ef-ad4435b71e51.png)

![image](https://user-images.githubusercontent.com/13268272/75297398-dffbc280-5883-11ea-88ce-7c8efc6dc0ba.png)

**Comment by okumujustine** [comment]
am getting this problem too, is there any solution for it

here is my screen shots
this my state, the emojiShow is to toggle the showing of the emoji picker
<img width="529" alt="Screen Shot 2020-03-19 at 9 16 24 AM" src="https://user-images.githubusercontent.com/22288040/77037588-bcc7bd00-69c2-11ea-8863-a86a61f71bf6.png">

here is the button cliked to change the state of the emoji picker
<img width="456" alt="Screen Shot 2020-03-19 at 9 24 01 AM" src="https://user-images.githubusercontent.com/22288040/77037882-67d87680-69c3-11ea-87fe-7f5721cd521b.png">
here is how the emoji picker is shown
<img width="711" alt="Screen Shot 2020-03-19 at 9 18 03 AM" src="https://user-images.githubusercontent.com/22288040/77037748-116b3800-69c3-11ea-82df-098b264efcc9.png">

whenever i change the emojishown state by clciking the button its displays this error

**Comment by ealush** [comment]
Hey @ximanWang and @okumujustine . Thanks for providing more details.

I am able to reproduce the error. This is only true for the initial render (or at least, until the full render of the picker). I suspect that I know what's causing this.

In short:
I placed a fallback for broken image files. Some emoji files are not present on the cdn, and instead of rendering a broken image tag, I remove them from the picker onError.

I'll try to play around with it, and maybe move this out of the state into ref.

**Comment by ealush** [comment]
Hey @ximanWang and @okumujustine .
OK, so it wasn't what I suspected, but I believe I made some progress.

Can you please try installing `emoji-picker-react@3.1.4-rc.1`? If it works for you without the state update issue, I'll push it to master.

**Comment by ealush** [comment]
Released `emoji-picker-react@3.1.4` which solves it.
