### ISSUE TITLE
Got an undefined when looking for a special character

### ISSUE THREAD

**Issue by TheMrP** [ealush/emoji-picker-react#144]
Hello, when I enter this :) I received the following error
![Screenshot_2020-04-29 emoji-picker-react - StackBlitz](https://user-images.githubusercontent.com/22499775/80629132-04a51f80-8a18-11ea-9fc2-2f174a471e2c.png)

**Comment by ealush** [comment]
Hey @TheMrP. I noticed the bug as well. Apparently I didn't consider special characters when building the emoji dictionary. It shouldn't throw anymore.

Thanks!
