### ISSUE TITLE
How to get the "emoji" by passing the unified code?

### ISSUE THREAD

**Issue by matheus-garcia** [ealush/emoji-picker-react#149]
Is there a way to get the emoji by a given unified code? I can't store the emoji itself, but the unified code i do.

**Comment by ealush** [comment]
Hey, @matheus-garcia. This is possible using third party libraries. Not sure if they are still up to date, but https://github.com/iamcal/js-emoji is the one I usually go to.

**Comment by matheus-garcia** [comment]
I've used that to convert the unified codes into emojis, if anyone ever needs, here it is:

```
const validateAvatar = (avatarUnicode) => {
    avatarUnicode = avatarUnicode.includes("-")
      ? avatarUnicode.split("-").map((value) => "0x" + value)
      : "0x" + avatarUnicode;

    Array.isArray(avatarUnicode)
      ? (avatarUnicode = String.fromCodePoint(...avatarUnicode))
      : (avatarUnicode = String.fromCodePoint(avatarUnicode));

    return avatarUnicode;
  };
```
