### ISSUE TITLE
How to disable skinTone picker?

### ISSUE THREAD

**Issue by mflash123** [ealush/emoji-picker-react#151]
How to hide(or disable) skinTone picker?
[Image](https://i.postimg.cc/W1Jf4p0D/2020-05-21-09-26-56.png)

**Comment by matheus-garcia** [comment]
Would enjoy this feature aswell, but I don't think there's an option to do that by now :(

**Comment by ealush** [comment]
@mflash123 from the screenshot it looks like you also want to disable the filter. is that correct?

@matheus-garcia is that what you want as well?

**Comment by matheus-garcia** [comment]
In my opnion it has to be two different properties, one from the search bar, another from the filter.

**Comment by mflash123** [comment]
> In my opnion it has to be two different properties, one from the search bar, another from the filter.

+1

**Comment by ealush** [comment]
Hey, both will be added in a minor version that will be added in the next couple of days.

**Comment by ealush** [comment]
@mflash123, @matheus-garcia 
I just published 3.2.0. It adds the following two props:
disableSkinTonePicker - disables just the skin tone picker
disableSearchBar - disables both the skin tone picker and the search bar. Why both? visually they are in the same spot and I figured it wouldn't look good with just the skin tone picker consuming that space.
