### ISSUE TITLE
Make group labels available to internationalization.

### ISSUE THREAD

**Issue by matheus-garcia** [ealush/emoji-picker-react#156]
Make Emoiji Groups labels properties for internationalization purposes: ["smileys & people","animals & nature","food & drink","travel & places","activities","objects","symbols","flags"]

ex: travelAndPlaces: "Lugares e Viagens"

**Comment by ealush** [comment]
That's a good point @matheus-garcia. Will be a part of a minor version to be released in the next couple of days.

**Comment by ealush** [comment]
@matheus-garcia 
I Did not add it to the documentation, would like your feedback on it first - but I added an option to modify the category titles.

The picker takes the following new prop: `groupNames` which takes an object of category keys and their translations. Whatever you don't change, defaults to the existing name.

Here's the full list of keys:

```
  smileys_people
  animals_nature
  food_drink
  travel_places
  activities
  objects
  symbols
  flags
  recently_used
```

**Usage example**
```js
<Picker groupNames={{
  smileys_people: 'yellow faces',
  animals_nature: 'cute dogs and also trees',
  food_drink: 'milkshakes and more',
  travel_places: 'I love trains',
  activities: 'lets play a game',
  objects: 'stuff',
  symbols: 'more stuff',
  flags: 'fun with flags',
  recently_used: 'did I really use those?!',
}}/>
```

![image](https://user-images.githubusercontent.com/11255103/83456624-b2b54680-a468-11ea-825c-8ac42fc571d1.png)

**Comment by matheus-garcia** [comment]
Hello, for me that's a perfect solution, there aren't many groups, so it wouldn't even bother to have these properties.
