### ISSUE TITLE
How exclude certain groups?

### ISSUE THREAD

**Issue by bhairava3** [ealush/emoji-picker-react#176]
Hi! This is the best emoji component, better optimized, no lags, etc.! Thank you for this wonderful job!
Can I turn off the display of some emoji categories?

**Comment by ealush** [comment]
Hey @bhairava3, thank you for this response. I appreciate it 🙏🏻

Hrm. This wasn't a feature, but it is now. If you use 3.4.0 you will have the groupVisibility prop that works similarly to the groupNames prop. You pass it a group name and a boolean indicating whether it is visible or not. Let me know if that works for you.

https://github.com/ealush/emoji-picker-react#disabling-categories

**Comment by bhairava3** [comment]
Thank you so much!

**Comment by yelnyafacee** [comment]
> Hey @bhairava3, thank you for this response. I appreciate it 🙏🏻
> 
> Hrm. This wasn't a feature, but it is now. If you use 3.4.0 you will have the groupVisibility prop that works similarly to the groupNames prop. You pass it a group name and a boolean indicating whether it is visible or not. Let me know if that works for you.
> 
> https://github.com/ealush/emoji-picker-react#disabling-categories

is this feature gone? I cannot find the `groupVisibility` or `groupNames` props anymore

**Comment by ealush** [comment]
No, the feature is not gone, it is just moved into the group config prop.
You can omit certain groups from it.
