### ISSUE TITLE
Remove console.log from /src/components/CategoriesNav/index.js

### ISSUE THREAD

**Issue by Nafaska** [ealush/emoji-picker-react#177]
The change added in the next commit https://github.com/ealush/emoji-picker-react/commit/3740cb531a358e13bfd013f1f47e0fbe74f0285b contains `console.log()` - https://github.com/ealush/emoji-picker-react/blob/master/src/components/CategoriesNav/index.js#L47.

It results in log messages in the production code.

**Comment by ealush** [comment]
Hey, sorry about that. Thank you for applying a PR so quickly. I merged it, and published a new version `emoji-picker-react@3.4.1`. 🙏🏻

**Comment by Nafaska** [comment]
Cool! Thanks for publishing the new version so quickly!
