### ISSUE TITLE
CSP headers fail due to "Function() use"

### ISSUE THREAD

**Issue by penfold45** [ealush/emoji-picker-react#181]
Due to this line of code 

`const globalObject = Function('return this')();
`

If I set the `Content-Security-Policy` then I also must set the value `unsafe-eval` which is not great.
Any change you could not use the string here and then there would not be the need to add `unsafe-eval`

Thanks

**Comment by ealush** [comment]
You are right. I will `try` getting window, and fall back to an empty object. This should be a sufficient solutions for nearly all use cases.

**Comment by ealush** [comment]
Should be fixed in `3.4.3`. Let me know if anything's missing.

**Comment by penfold45** [comment]
Thanks that looks like it works much better. However. I did not notice but you are also injecting inline css which would require `unsafe-inline` to be set in the header which is again not great.

Is there a way to stop the inline styles? I am using `INLINE_RUNTIME_CHUNK=false npm run build` which has removed all the other inline styles.

Thanks
