### ISSUE TITLE
cdn.jsdelivr responds 403

### ISSUE THREAD

**Issue by suiramdev** [ealush/emoji-picker-react#182]
It seems that the module is retrieving emojis as PNG from [cdn.jsdelivr.net ](url) but, on my side, it is giving me a 403 error:
![image](https://user-images.githubusercontent.com/71449142/112451132-6ddf0100-8d55-11eb-9dc0-bdc4a6c2b1b3.png)
For the following reason:
![image](https://user-images.githubusercontent.com/71449142/112451373-b696ba00-8d55-11eb-9789-5239cb947759.png)

Wouldn't it be better to retrieve the emojis from [https://raw.githubusercontent.com/iamcal/emoji-data/master/img-apple-64/1f1ea-1f1f9.png](url) for example ?

**Comment by jimaek** [comment]
According to https://github.com/iamcal/emoji-data you should be using the NPM version, which works fine.
https://cdn.jsdelivr.net/npm/emoji-datasource@6.0.1/img/apple/sheets/32.png
https://cdn.jsdelivr.net/npm/emoji-datasource-apple@6.0.1/img/apple/64/0031-fe0f-20e3.png

**Comment by ealush** [comment]
Hey @suiramdev, @jimaek 
Sorry that you're experiencing this.

I'll look into it and make the switch if I see that indeed it works better. In the meantime, you can manually provide an alternative CDN path to the picker.

Here I describe how to do it: https://github.com/ealush/emoji-picker-react/issues/157

**Comment by ealush** [comment]
By the way, your users won't experience the broken images. I remove them from rendering when there's an error on any of the images. - so no worries about that.

**Comment by ealush** [comment]
Just published 3.4.4 with the updated cdn URL. It does indeed seem to work better.

Thank you @suiramdev for reporting and @jimaek for suggesting the alternative URL.

**Comment by suiramdev** [comment]
Happy for helping you 👍🏻 Thank you also for your reactivity
