### ISSUE TITLE
groupVisibility does not hide recentlyUsed

### ISSUE THREAD

**Issue by Bnaya** [ealush/emoji-picker-react#191]
![Screen Shot 2021-05-19 at 13 23 53](https://user-images.githubusercontent.com/1304862/118797621-765f3e00-b8a5-11eb-934d-8357c8310ecc.png)

Repro:
https://stackblitz.com/edit/emoji-picker-react-g2gmag?file=index.js
Click on an emoji, refresh internal browser, see recently used group appear

**Comment by ealush** [comment]
Thanks for the report, @Bnaya

This indeed looks like an oversight on my end. [Fixed](https://github.com/ealush/emoji-picker-react/commit/74f83f86ade3f2cc31f0d2b7740ce4ecd111ae81) in 3.4.5.

BTW, group names are snake_case, so it should be `recently_used`
