### ISSUE TITLE
TypeError: can't access property "current", u is undefined

### ISSUE THREAD

**Issue by GabrielNumaX** [ealush/emoji-picker-react#196]
this happens when clicking on a Recently Used emoji

![emojiBug](https://user-images.githubusercontent.com/37051017/121304057-3c94bc80-c8d2-11eb-8472-ff0992ff230c.png)

**Comment by ealush** [comment]
Yep, I'm seeing it too. Should be fixed in `3.4.8`. LMK if that works for you now.
