### ISSUE TITLE
document.createElement is not a function in React Native App

### ISSUE THREAD

**Issue by janet-kang** [ealush/emoji-picker-react#203]
I am getting a `document.createElement is not a function` error when I import `Picker` into my react native app. Seems like `createElement` is not supported by react native. Any solutions?
![Screen Shot 2021-08-27 at 12 49 57 PM](https://user-images.githubusercontent.com/52132215/131181358-71fd3ded-0a1f-49e0-9576-62955532e6ab.png)

**Comment by ealush** [comment]
Hey, thanks for reaching out. Emoji picker react is a library for the web, and cannot be used on react native.
