### ISSUE TITLE
[Feature] There should be an option to add a placeholder text to the emoji-search input field

### ISSUE THREAD

**Issue by Roy-05** [ealush/emoji-picker-react#207]
I would like to add some placeholder text to the emoji-search input field. Something like "Search Emoji...".

It should be pretty straightforward by passing a prop to the picker, or by even exposing a ref to the input field, however I do not see either of the two options available currently.

Please consider, TIA!

**Comment by ealush** [comment]
Hey, sorry for responding late. I have been very busy working on other projects.

This seems reasonable, considering the fact that the picker allows for providing category names. If you feel like contributing this feature, go ahead, alternatively, I'll add it to the new version tracking.

**Comment by ErezBiren** [comment]
Hi, I'll be glad to take it.

**Comment by ealush** [comment]
@ErezBiren, cool. It's yours :)
