### ISSUE TITLE
hide based on focus-out/blur event

### ISSUE THREAD

**Issue by ashish-stock-smart** [ealush/emoji-picker-react#211]
Requirement:
I want to close emoji panel when panel hits blur/focusout DOM event. But currently I'm unable to capture these events.

Below is my code sample.

`
<Picker
            preload={true}
            onEmojiClick={onEmojiClick}
  />

        let elms = document.getElementsByClassName("emoji-picker-react");

        if (elms.length > 0) {
          let elm = elms[0];

          elm.addEventListener('blur', (event) => {
            console.log("event blur123: ", event);
            setIsSelectorVisible(false);
            return event;
          });
  
          elm.addEventListener('focusout', (event) => {
            console.log("event focusout: ", event);
            setIsSelectorVisible(false);
            return event;
          });
        }
`
Please share if there is any other solution.

**Comment by ealush** [comment]
Hey,
sorry for taking this long to respond. I have been very busy on other projects. I believe that what you're after should be done the other-way-around. Not all parts of the picker have a focusOut or a blur event, so clicking outside of the picker won't trigger it in your way as well.

What I've done in similar cases is a general-case `isAnOutsideClick` function, which takes the target element as its argument.
Then, whenever relevant (for example - when the picker is open) - add a click event onto body. On click, check if the click target is a descendant of your desired element (for example, our picker). This should cover most cases, and require the picker to provide you with extra apis.
