### ISSUE TITLE
localStorage check in RecentlyUsed is failing to detect that local storage isn't present

### ISSUE THREAD

**Issue by MarkRogersEx** [ealush/emoji-picker-react#213]
I've used the emoji picker in two mobile hybrid apps one for android and one for ios's apple web kit.
In those apps, an error is being thrown and the picker is failing because its trying to use localStorage which is often not available in mobile hybrid apps.

For some reason the global check (`'localStorage' in globalObject`) isn't enough.  It would probably be good to just do a if(!localStorage) {return;} in addition to the other check.

https://stackoverflow.com/a/25108867/25847  they mention if(window.localStorage)

**Comment by ealush** [comment]
Yes. This looks right. Sorry for taking the time. I've been busy working on other projects. I'll get this fix pushed soon.

**Comment by ealush** [comment]
Fixed in 3.4.11
