### ISSUE TITLE
Skin tone not been updated

### ISSUE THREAD

**Issue by albertodeavila** [ealush/emoji-picker-react#215]
ey @ealush ! 

I've figured out that on this new version, if you specify any skin tone, it's been ignored: 
![image](https://user-images.githubusercontent.com/9431295/146381949-3489cbd6-d90b-4dfd-8988-63dde4b6d8f5.png)

It was working on the version 3.4.8:
<img width="1553" alt="Screenshot 2021-12-16 at 14 36 07" src="https://user-images.githubusercontent.com/9431295/146382357-623cc8ab-3881-4542-aca1-b3255bbb8fcd.png">

but not since this version 

I've been using the [demo](https://stackblitz.com/edit/emoji-picker-react?file=index.js) to reproduce the error

[Here you have a Loom that can help](https://www.loom.com/share/793bc68b042f4018830acccc4899aa83)

Thanks!

**Comment by ealush** [comment]
Hey @albertodeavila, thank you for reporting!

I tested and can confirm this issue exists in 3.4.11.

I just released `3.4.12` that fixes it. Let me know if that works for you

**Comment by albertodeavila** [comment]
Awesome! Thanks for this quickly fix!
