### ISSUE TITLE
Some emoji icons can't show properly when selected

### ISSUE THREAD

**Issue by WinniePooh04** [ealush/emoji-picker-react#238]
Hello anyone please share to me if know this issues. 

I'm using emoji picker with react quill, when I selected the crying icon the icon is shown as square shape and can't able to show the emoji icon properly. Please check on below image.
<img width="194" alt="Untitled" src="https://user-images.githubusercontent.com/26960632/154266875-98948e90-5b0c-47cc-b362-326ad07f8fb6.png">

**Comment by ealush** [comment]
Emojis display are OS dependent. If you want consistent rendering of emojis in your app, you should render emoji images instead of native emojis.

**Comment by WinniePooh04** [comment]
> 

Thank you so much your kind and quick reply. 
If you don't mind, could you please also share me references of how to do render emoji images?

**Comment by WinniePooh04** [comment]
Thanks now can solve the issue

**Comment by WinniePooh04** [comment]
Sorry by the way how can I get the emoji-data-source size 16?
Looking forward your kind response. Thanks.

**Comment by ealush** [comment]
@WinniePooh04 there doesn't seem to be a 16, here you can inspect the available sizes and styles: https://github.com/iamcal/emoji-data
