### ISSUE TITLE
The emoji icon design in dialog and selected emoji icon design not same in shown in react quill editor

### ISSUE THREAD

**Issue by WinniePooh04** [ealush/emoji-picker-react#239]
In the emoji dialog the icon design is 'apple' icon design but I selected the emoji icon and showed in react quill editor the icon design is different. Any idea or suggestion for that issue?
Please check below image for this issue.
<img width="262" alt="Untitled" src="https://user-images.githubusercontent.com/26960632/154286762-51ef9778-5825-4a4f-839e-8e4279b42a67.png">

With Best Regards.

**Comment by ealush** [comment]
This is as intended. In the picker you see images of the emojis, but when you use them outside, you get the OS rendered emojis. You should consider either displaying "native" emojis in the picker, or switch to images when you actually consume them outside of the picker.
