### ISSUE TITLE
The distance between emoji

### ISSUE THREAD

**Issue by wuqiren** [ealush/emoji-picker-react#246]
Look at this picture.
![image](https://user-images.githubusercontent.com/54806027/160081808-623bbf40-533d-4e1c-a12b-5082811113d3.png)
![image](https://user-images.githubusercontent.com/54806027/160081860-a42c2c97-f060-4dea-9d3e-0a044bffebd6.png)

The right side of the emoji doesn't take up space.

**Comment by ealush** [comment]
I really don't think that's an image with the picker. You should probably increase the letter spacing in your textarea element.

**Comment by wuqiren** [comment]
ok  Thanks  It's  a good idea
 I've solved it.
