### ISSUE TITLE
JSX required

### ISSUE THREAD

**Issue by cdbeland** [ealush/emoji-picker-react#252]
I tried to set up this picker based on the example code. I kept getting the error "emojio-picker-react SyntaxError: expected expression, got '<'" on the line with "<div>". Apparently this is JSX and not valid JavaScript, and requires translation before it can be run in a web browser. This should probably be noted in the documentation, and a non-JSX example would be helpful. Thanks!

**Comment by ealush** [comment]
Hey @cdbeland, I'm pretty sure the picker does not ship with raw JSX, and you must be experiencing something different. Can you share more about your issue?
