### ISSUE TITLE
Error when importing dynamically with NextJS

### ISSUE THREAD

**Issue by elmasse** [ealush/emoji-picker-react#259]
Hello,

I tried to upgrade to `v3.6` and hit an issue when dynamically importing the library onto my nextjs app. 

This works with `v3.5.1`:

```
const Picker = dynamic(() => import('emoji-picker-react'), { ssr: false })


``` 

When using `v3.6` the error shows:

```
error - ./src/design/emojipicker.js:8:29
Module not found: Can't resolve 'emoji-picker-react'
   6 | import Button from './button'
   7 | 
>  8 | const Picker = dynamic(() => import('emoji-picker-react'), { ssr: false })
     |                             ^
   9 | 
  10 | export default function EmojiPicker ({ onSelect, ...props }) {
  11 |   const [referenceElement, setReferenceElement] = useState()
```

**Comment by ealush** [comment]
Hey @elmasse, thanks. Can you please provide a repro that I can play with? I don't use nextjs myself.

**Comment by elmasse** [comment]
Hey @ealush thanks for your quick replay. It's quite strange, I cannot reproduce it with a simple example using nextjs and your library.

I'm gonna close the issue for now.

Thanks!
