### ISSUE TITLE
[FEATURE REQUEST] When the user is focused on an emoji and starts typing picker should start filtering

### ISSUE THREAD

**Issue by nadeemkhedr** [ealush/emoji-picker-react#269]
Currently, When I click on arrow down to highlight an emoji and start typing, nothing happens

It would be nice to auto focus on the filter and continue filtering

**Comment by ealush** [comment]
That could be a useful feature. Adding it to the feature requests for the new version.

**Comment by ealush** [comment]
Hey @nadeemkhedr 
I just incorporated your suggestion into the next major version, and I have to say - although it may present some edge-case bugs around global keyword listeners, I am pretty satisfied with its ergonomics.

You can see it live here: https://codesandbox.io/s/floral-rgb-z2gkzp?file=/src/App.tsx

**Comment by ealush** [comment]
Implemented in v4, closing now.
