### ISSUE TITLE
[BUG] When clicking down arrow sometimes I can't jump to a new group 

### ISSUE THREAD

**Issue by nadeemkhedr** [ealush/emoji-picker-react#270]
This issue is weird, 

Sometimes when I click down, and I am at the end of a group, doesn't go to the next group and stays on the selected emoji 

In this example it works fine, When I click down it goes to `SMILEYS & PEOPLE`
![2022-09-08_18-56-38](https://user-images.githubusercontent.com/180256/189181408-bc9be563-37e7-4813-a064-2f86d1b0a07b.png)

But here when I  press down it stays on the sea shell and doesn't go to the icon bellow 
![2022-09-08_19-07-39](https://user-images.githubusercontent.com/180256/189183539-73596b4f-a851-4817-a07b-3631dfa121c9.png)

**Comment by ealush** [comment]
Yes, I can confirm I see this.
Luckily, this has been worked on in the new version of the picker. Here you can try it out https://codesandbox.io/s/floral-rgb-z2gkzp?file=/src/App.tsx

It seems to be functioning correctly, and you can already install it by: `npm i emoji-picker-react@rc` if you find the new version useful.

**Comment by ealush** [comment]
V4 has been released, v3 will not be modified to support this as well.
