### ISSUE TITLE
Add the src/components/emoji/Emoji component to the export

### ISSUE THREAD

**Issue by stas-raranetskyi** [ealush/emoji-picker-react#271]
it would be great if you added the Emoji component to version 4 to display a picture by hex code

For example
```
import EmojiPicker, { Emoji, EmojiClickData } from 'emoji-picker-react';

const App: React.FC = () => {
	const [selectedEmoji, setSelectedEmoji] = useState<string>('');

	function onClick(emojiData: EmojiClickData) {
		setSelectedEmoji(emojiData.unified);
	}
	return (
		<>
			<Emoji unified={selectedEmoji} />
			<EmojiPicker onEmojiClick={onClick} />
		</>
	);
};
```

**Comment by ealush** [comment]
@stas-raranetskyi, that's an excellent idea, and I see how it can improve the picker's usability.

RC.33 now includes this change, you can see it live here:
https://codesandbox.io/s/floral-rgb-z2gkzp?file=/src/App.tsx

and install it here: `emoji-picker-react@4.0.0-rc.33`.

The following props are required:

```js
unified
emojiStyle (apple/native...)
```

And for convenience, the following is allowed as well
```js
size={22}
```

**Comment by ealush** [comment]
Please, let me know if that works for you, and also, are there any other issues you experience using version 4? I would love to release it as the main version.

**Comment by stas-raranetskyi** [comment]
Thanks for the quick response to my issue

Everything works perfectly
