### ISSUE TITLE
EmojiPicker inside form triggers form submit when selecting an emoji

### ISSUE THREAD

**Issue by antoHuman** [ealush/emoji-picker-react#272]
Emoji buttons have no specified `type` so they default to `submit`. I think this is quite easy to fix, as long as you do not have any logic associated with form submitting (does not seem like it). I can open a PR if necessary.

I am on Chrome, Version 106.0.5249.62 (Official Build) (64-bit).
The library version is 4.0.3.

Great work btw!

**Comment by ealush** [comment]
Hey @antoHuman, thank you for reporting the issue.

You are right, I added `type="button"` to the emojis. Can you confirm that this works for you in `4.0.4`?

**Comment by maticrivo** [comment]
But it is still happening when clicking the skin tone selector button..

**Comment by ealush** [comment]
🤦‍♂️
Forgot these.

Could you try please 5.0.5?

**Comment by maticrivo** [comment]
now its perfect 👌

**Comment by antoHuman** [comment]
I can confirm that it works for me as well! Thanks a lot! Guess you can close this if you want
