### ISSUE TITLE
How to specify EmojiPicker size with percentage like `100%`

### ISSUE THREAD

**Issue by exKAZUu** [ealush/emoji-picker-react#281]
The current code seems to accept pixel numbers, but, we want to use percentages.
https://github.com/ealush/emoji-picker-react/blob/dc35f0990c628ef11a7f9276e155f65f2cdcc201/src/components/main/PickerMain.tsx#L39-L42

**Comment by ealush** [comment]
Good idea @exKAZUu. Let's do this. Just published 4.3.0 that supports any CSS property as a string.

**Comment by ealush** [comment]
Closing since 4.3.0 solves this.

**Comment by exKAZUu** [comment]
We've confirmed 4.3.0 fit in our use case. Thanks!
