### ISSUE TITLE
emojiVersion does not filter correctly when skinTone is used

### ISSUE THREAD

**Issue by mna2001** [ealush/emoji-picker-react#286]
Following on from issue #275 

I think it only works for the NEUTRAL skinTone, when I pass in a different defaultSkinTone a much longer list of emojis are displayed and some invalid one are included. I am using emojiVersion "0.6"

BTW Just started using the package and very impressed - very simple to use and looks good

**Comment by ealush** [comment]
@mna2001 oh my! I think you are right.
I just released 4.4.2 that fixes that. Thank you for bringing it to my attention. 🙏

Also, so glad you like it!

**Comment by mna2001** [comment]
That works for me - will close the issue
