### ISSUE TITLE
how to solve it?

### ISSUE THREAD

**Issue by Youngpro95** [ealush/emoji-picker-react#288]
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/44990343/196774401-bfe933e6-4cd3-4ec6-b8b0-eed530d44af3.png">

Hello i'm a junior developer
how to solve that problem?? i cant find some docs

thank you for read my question
have a nice day

**Comment by ealush** [comment]
Hey @Youngpro95 
Welcome!
No need to solve this. The picker tries to download emojis which may fail due to a network error or the images missing on the cdn.

The picker auto handles these errors for you so the picker still renders correctly without the missing emojis.

**Comment by Youngpro95** [comment]
@ealush 
Thank you for your reply!!

it seems like it is a failure to keep downloading files from the cdn server, so can we ignore this error for now?

**Comment by ealush** [comment]
Yes. The files are emoji images, which I can't control.

If they fail t load, the picker just doesn't render them. They can be safely ignored.

**Comment by Youngpro95** [comment]
Thank you for your reply!!
and thanks your librarys it's really easy to use emoji 👍

Have a nice day!!
