### ISSUE TITLE
Only showing 3 emojis per line

### ISSUE THREAD

**Issue by bennetmi** [ealush/emoji-picker-react#295]
Hello,

After installing the package, the box only loads with 3 emojis per line, leaving a lot of empty space.
Is there a way to extend that so that it fills the whole line with emojis instead?

![Screenshot 2022-11-10 112411](https://user-images.githubusercontent.com/107875710/201164323-e47ce025-0046-4690-8830-568e9fbe4ea2.png)

**Comment by ealush** [comment]
Hello,
Can you please create a repro on codesandbox?

I would assume you have a conflicting css rule (probably on css grid) that limits the grid size, as this isn't the normal picker behavior.

**Comment by bennetmi** [comment]
I did indeed. Had an inline-block display conflicting with it, thank you for the help.
