### ISSUE TITLE
How to override aside.EmojiPickerReact.epr-main CSS <STYLE> GENERATED IN THE <HEAD>?

### ISSUE THREAD

**Issue by yelnyafacee** [ealush/emoji-picker-react#312]
How to override `aside.EmojiPickerReact.epr-main` CSS STYLE?

ALL the generated `<style>` CSS is APPENDED TO THE TOP OF THE <HEAD>

HOW TO OVERRIDE IT? `Customizable styles`?

**Comment by ealush** [comment]
Most non essential style attributes can be overridden with css variables. See the doc's section on customization
