### ISSUE TITLE
Custom Category with dynamic list of emojis

### ISSUE THREAD

**Issue by 0xM4m4n** [ealush/emoji-picker-react#318]
Hello! I was wondering if it is possible to create a "custom" category in the picker that loads a list of emojis from img urls?
I guess im wondering if the feature like on slack or discord is possible so you can support user uploaded or client set custom emojis in the picker. I saw there was an issue on this a couple years ago but I don't see any changes in the code. 

Awesome product tho!

best,
M4

**Comment by ealush** [comment]
Hey @0xM4m4n,
Technically - it is possible, and should probably not even be that hard to implement. I currently have a few conflicting design ideas for this feature, but all would probably piggyback on the category customization APIs, something of the sort of:

```js
[
  {
    category: 'custom',
    icon: 'some_image_url.svg',
    name: 'Custom Icons',
    images: [{name: 'some_name', search: ['key1', 'key2'], imageUrl: 'someImageUrl.png' }]
  },
  {
    category: 'suggested',
    name: 'Recently Used'
  },
  {
    category: 'smileys_people',
    name: 'Faces...'
  },
];
```

I currently don't have the time to work on it myself, but I would love to assist if you want to take a stab at it. My assumption is that it shouldn't take more than a couple of days to get this released.

**Comment by talperets** [comment]
Hey, I would love to add this feature to the project

**Comment by ealush** [comment]
> Hey, I would love to add this feature to the project

You're on it

**Comment by ealush** [comment]
Hey, just spent the past couple of hours to build custom emoji support. You can try it, and I would love to hear your feedback and if it works well for you. All the details are here: #358
