### ISSUE TITLE
A .png file of an emoji is missing

### ISSUE THREAD

**Issue by Omm-Pani** [ealush/emoji-picker-react#326]
On calling the component................... an error in the console appears.
![Screenshot (29)](https://user-images.githubusercontent.com/99495004/224337577-24ac4be3-becd-4b60-85f1-10da60381185.png)

On following the link we get:
![Screenshot (30)](https://user-images.githubusercontent.com/99495004/224338218-4fd684e4-01a4-408b-a03a-c07bac7a3e14.png)

**Comment by madhavdutta** [comment]
Did anyone find the solution for this?

**Comment by ealush** [comment]
Nothing much to do about this, and this won't change the behavior of the picker itself. This is a missing emoji that exists in the data-source but not in the CDN. I might exclude it, but it doesn't lead to any issue in the picker, as the picker itself has built-in recovery for missing images.

**Comment by AdnanRibic** [comment]
> 

Can you please exclude it as I can see that we all have the same issue? There are reports here as well on Stackoverflow with the same error. If you need help, I will gladly make a PR. Tnx

**Comment by ealush** [comment]
This is being handled in #336 that's currently in review, thanks @AdnanRibic

**Comment by YauhenMurachou** [comment]
> 

Hello. Is this feature (unicodeToHide) implemented?
I use emoji-picker-react v 4.4.11, and I see this property in source code.
But in my react application I have this type error:
![image](https://github.com/ealush/emoji-picker-react/assets/77886950/e9972ead-9058-4eac-a66e-eb8bfc3e8fbc)

![image](https://github.com/ealush/emoji-picker-react/assets/77886950/17c24411-5152-4ec3-ba5d-7811ea0c8453)

![image](https://github.com/ealush/emoji-picker-react/assets/77886950/e0995353-3a95-46c1-acc2-40deea02615d)

**Comment by ealush** [comment]
@YauhenMurachou `unicodeToHide` is internal and not exposed. A more extensive API for hiding/modifying emojis is being worked on.
