### ISSUE TITLE
How can translate categories labels and `Frequently/Recently used` text?

### ISSUE THREAD

**Issue by THammami01** [ealush/emoji-picker-react#328]
Hi, I am using `i18n` in a React TypeScript app and I would like to translate the text of all categories `Recently Used`, `Frequently Used`, `Smileys & People`, ...
I can see that the text I am looking for is located in `src/config/caterogyConfig.ts`, and I'd like to know what is the best way to translate it for my case.

**Comment by THammami01** [comment]
Hi, I am using `i18n` in a React TypeScript app and I would like to translate the text of all categories `Recently Used`, `Frequently Used`, `Smileys & People`, ...<br/>
I can see that the text I am looking for is located in `src/config/caterogyConfig.ts`, and I'd like to know what is the best way to translate it for my case.

**Comment by ealush** [comment]
See the 'categories' prop in the docs. It allows you to set custom names per category.
