### ISSUE TITLE
Looking for emoji with a smile with broken teeth which expresses self-deprication humor

### ISSUE THREAD

**Issue by mkieblesz** [ealush/emoji-picker-react#332]
First of all thank you for amazing package!

I know this may seem strange, but I am looking for this emoji which was used frequently on boybuilding forums and just can't find it. I searched google, looked through chatGPT and nothing, not even close.

I would be grateful if you could point me to the right direction of where to look for it. Thanks!

**Comment by dlibis** [comment]
@mkieblesz can you draw from memory how it looks?

**Comment by mkieblesz** [comment]
@dlibis I would defined it as a "grinning face with smiling eyes with broken teeth". The grin took most of the face though. I interpreted this as toung and cheek, self depricating but also a little bit braggadocious.

**Comment by mkieblesz** [comment]
Got it. It was actually beaten face heh

![beaten-emoji](https://github.com/ealush/emoji-picker-react/assets/20416930/7fd65d3c-a583-4032-875c-076c90984901)
