### ISSUE TITLE
Bug: Emoji picker is trying to search when searchDisabled={true}

### ISSUE THREAD

**Issue by carlosvalv** [ealush/emoji-picker-react#333]
When I click to the modal and I type something enters in mode "search" although the property searchDisabled is true.

Before typing text
![image](https://user-images.githubusercontent.com/28527787/233347668-6636d87a-f194-4627-8125-50d97e68af06.png)

After typing some text
![image](https://user-images.githubusercontent.com/28527787/233347971-b1eb57ac-d541-4073-80d0-d2e1cd91640d.png)

I think it's trying to search anyway, and the emoji categories turn disabled. 
Thanks for your time 😄.

**Comment by ealush** [comment]
Yes, this seems like a bug. I will have to take a look at it when I get home from my vacation.

Thank you for reporting this.

**Comment by nati-elmaliach** [comment]
@ealush please assign it to me :)

**Comment by ealush** [comment]
Fixed by @nati-elmaliach  in 4.4.9!
