### ISSUE TITLE
Emoji Picker Issue: global not defined

### ISSUE THREAD

**Issue by KartikeyKakaria** [ealush/emoji-picker-react#335]
I wanna use the emoji picker extension, but it bugs my whole app and gives this error
Uncaught ReferenceError: global is not defined
 js http://localhost:8000/node_modules/.vite/deps/emoji-picker-react.js?v=7919ba0a:13
http://localhost:8000/node_modules/.vite/deps/chunk-DFKQJ226.js?v=7919ba0a:8
<anonymous> http://localhost:8000/node_modules/.vite/deps/emoji-picker-react.js?v=7919ba0a:1242

**Comment by ealush** [comment]
See troubleshooting section in the docs.

**Comment by KartikeyKakaria** [comment]
Thanks 👍
