### ISSUE TITLE
Improve functions naming convention in suggested.ts file

### ISSUE THREAD

**Issue by ErezBiren** [ealush/emoji-picker-react#339]
In the `suggested.ts` file, I noticed that the functions `setsuggested` and `getsuggested` are written in lowercase. 
I was wondering why they are not written as `setSuggested` and `getSuggested` using camel case.

If it is indeed a mistake, I would be happy to submit a pull request to fix it.

**Comment by ealush** [comment]
Hey! yeah, sure. Why not. Go ahead. It's probably just me using multiple cursors or find/replace. Feel free to edit that.

Thank you!
