### ISSUE TITLE
i wish there will be `how to run` section at readme file

### ISSUE THREAD

**Issue by shootermv** [ealush/emoji-picker-react#363]
it can be nice to add
section with instructions of how to run the project locally
like:  1. clone the repo `git clone https://github.com/ealush/emoji-picker-react `
some projects has a section like this

**Comment by talisraeli** [comment]
@ealush I'd like to be assigned for this.

**Comment by ealush** [comment]
@shootermv, good idea. Let's do this.
Thanks @talisraeli, all yours!
