### ISSUE TITLE
Missing & double emojis on Windows 11

### ISSUE THREAD

**Issue by moverware** [ealush/emoji-picker-react#366]
Hey there, we noticed an issue with our app for users on Windows 11. We tested this with this codesandbox to ensure it wasn't our app: https://codesandbox.io/s/emoji-picker-react-4-z2gkzp

And it reproduces. Here is a screenshot of the issue:
![image](https://github.com/ealush/emoji-picker-react/assets/6676299/a667b6a0-c8f6-4484-ac7e-e8b768e5dee2)

**Comment by ealush** [comment]
Hmm. Unfortunately, there's not much to do, and this also means that win-11 users won't be able to view these emojis when used outside of the picker, or even if sent from an iOS device. These are simply not implemented by the OS. My suggestion is to use "apple" emoji style.

**Comment by Cribug8080** [comment]
How to fix it?

**Comment by ealush** [comment]
Use `apple` emoji style, but it will still not work with regular input elements.
