### ISSUE TITLE
Can't load custom emojis from an API call.

### ISSUE THREAD

**Issue by burzumumbra** [ealush/emoji-picker-react#369]
I'm trying to use custom emojis, but only when I load them from a static source it works, there's something I could be missing here?

<img width="581" alt="image" src="https://github.com/ealush/emoji-picker-react/assets/4171009/bafca542-4d27-4d20-8395-f33aa645ebfe">

**Comment by ealush** [comment]
Hmm. I have an assumption, but I am not sure. Can you share a codesandbox with a repro so that I can try to fix the issue?

Thanks!

**Comment by burzumumbra** [comment]
> Hmm. I have an assumption, but I am not sure. Can you share a codesandbox with a repro so that I can try to fix the issue?
> 
> Thanks!

Thanks for the fast reply, I'll have to find an alternative for the API, since it's a corporate app I can't expose it in Codesandbox. I'll came back to you after I have all that setup, again thanks.

**Comment by ealush** [comment]
Sure. Let me know once you have it. In the meantime, if you can just describe what's the flow that's happening, it would help.

I am assuming what you do is something like this:

1. Mount your app (with the picker)
2. Fetch some emojis from an API
3. Add them as a prop

Could you try just to help me debug try something like this:

```js
<Picker customEmojis={emojis} key={`${emojis.length`}`}/>
```
Does it change anything?

**Comment by ealush** [comment]
@burzumumbra try 4.5.9. should work

**Comment by burzumumbra** [comment]
@ealush Sorry for the delay providing the code sample, but thanks for that speed answering to this issue, I'll check that version later today and let you know how it went, thanks.

**Comment by burzumumbra** [comment]
@ealush Sorry for taking time to reply, v4.5.13 and the key prop did solved.
<img width="473" alt="image" src="https://github.com/ealush/emoji-picker-react/assets/4171009/6f247748-71f5-4fb9-8f0b-a2bf344ce867">

**Comment by ealush** [comment]
@burzumumbra awesome. Fwiw, should work without the key prop now.
