### ISSUE TITLE
aria-label and title in Clear button

### ISSUE THREAD

**Issue by Dominiczeq7** [ealush/emoji-picker-react#380]
There is a need to add an aria label and title to the Clear button. I added manually what I highlighted. It would be good to include it in the code. I can declare myself to do it as I get access.
![393085391_1597730830981095_7371333784041661965_n](https://github.com/ealush/emoji-picker-react/assets/48733713/feb0d779-600e-4d34-a027-fe858ec31bf2)

**Comment by ealush** [comment]
Yes, feel free to add it to the picker. I will support this PR.
