### ISSUE TITLE
emoji style doesnt work

### ISSUE THREAD

**Issue by sedanurakcil** [ealush/emoji-picker-react#386]
Emoji ClickData returns an emoji with style type "native".  apple or google style doesnt work .

**Comment by sedanurakcil** [comment]
I understand but I want to use emoji in text string and url is used witth react img component or Emoji component.

**Comment by ealush** [comment]
Native emojis are rendered by the OS, nothing much we can do to change how they appear.

**Comment by sedanurakcil** [comment]
Okay , thanks for reply
