### ISSUE TITLE
How to detect skin-tone change

### ISSUE THREAD

**Issue by wfischer42** [ealush/emoji-picker-react#394]
I want to be able to set and update a user default skin tone preference when the user changes the skin tone in the emoji picker component. Ideally, this would be through a simple `onSkintoneChange` event, or something similar. Currently the user has to select an emoji before the parent can see the skin tone preference.

Is there any built-in way to do that currently? Otherwise, I'd love it as a feature.

**Comment by ealush** [comment]
Hi, @wfischer42 this sounds right and pretty useful. Would you like implementing yourself it with my support? I think that your callback proposal can work pretty well.
