### ISSUE TITLE
unicode emojis

### ISSUE THREAD

**Issue by Badlapje** [ealush/emoji-picker-react#395]
I hope this isn't in the docs somewhere and i missed it, but are the emojis unicode?  

My usecase: I'd use these emojis in a sms-text so i need them to be unicode.

There is a unified field in the emojiObject, but that's not the same as unicode as far as i can see?

**Comment by ealush** [comment]
In general, yes, the emojis are unicode, meaning that if you use the emoji icon that you get from the click handler, you should be able to use it later on. The unified is the unicode code, but not the actual unicode character, if that makes sense.

**Comment by Badlapje** [comment]
It does, much obliged for the quick response!
