### ISSUE TITLE
Optimize rendering by using react-virtuoso

### ISSUE THREAD

**Issue by sadiqsalau** [ealush/emoji-picker-react#405]
Hi, this is more of a suggestion because of how slow it is on mobile device. We could optimize the rendering by using a package such as react-virtuoso.

**Comment by ealush** [comment]
I have taken several stabs at using virtualization libraries, but does to the very unequal emojis grid, that are nested within categories - it makes it quite difficult to pull off. If you'd like to try, go for it.
