### ISSUE TITLE
Feature request: Possible to globally exclude certain emoji?

### ISSUE THREAD

**Issue by rambling-ai** [ealush/emoji-picker-react#408]
I'm making an app for my young kids and I don't want them accidentally sending eggplants and peaches to grandma :laughing: 

I tried removing the specific entries from `src/data/emojis.ts` and `src/data/emojis.json` but that didn't work, is there any official way to suppress certain spicy emoji?

**Comment by luantrasel** [comment]
I would also need a similar function, in my case I'd need to remove some emojis where the unicode string is too big (more than 30 characters)

**Comment by ealush** [comment]
Hi! Yep. Added this feature right now, should be available in emoji-picker-react@4.10.0.

Usage is quite simple, just add the the unified emoji code to the new hiddenEmojis prop:

```
<Picker hiddenEmojis={["1f604", "1f60d", "1f607"]} />
```

We certainly want to avoid sending an eggplant to grandma.

**Comment by thiagofuzaro** [comment]
> Hi! Yep. Added this feature right now, should be available in emoji-picker-react@4.10.0.
> 
> Usage is quite simple, just add the the unified emoji code to the new hiddenEmojis prop:
> 
> ```
> <Picker hiddenEmojis={["1f604", "1f60d", "1f607"]} />
> ```
> 
> We certainly want to avoid sending an eggplant to grandma.

This was exactly the feature I needed! Do you have any predictions on when it will be available?

**Comment by ealush** [comment]
It's out on 4.10. If that doesn't show try flushing node_modules. Tested recently and it worked for me
