### ISSUE TITLE
Emoji are not appearing properly in Windows Chrome Browser

### ISSUE THREAD

**Issue by bhupendra1011** [ealush/emoji-picker-react#417]
Hi , I am using `emoji-picker-react": "^4.7.1"` , on Mac emojis are appearing fine but on windows 10 , chrome (v 122) I get emoji panel as below. : some emojis are empty recangles

![image](https://github.com/ealush/emoji-picker-react/assets/5452261/453e3441-b41c-4714-a0cd-aa1a923f6a91)

Using Emoji Picker as below :
   ```
  const handleEmojiClick = (emojiObject: {emoji: string; names: string[]}) => {
    setMessage(prev =>
      prev ? prev + '  ' + emojiObject.emoji : emojiObject.emoji,
    );
  };
 <EmojiPicker
        style={styles.emojiPicker}
        onEmojiClick={handleEmojiClick}
        theme={ Theme.dark}
        suggestedEmojisMode={SuggestionMode.RECENT}
        className="chatEmojiPicker"
        lazyLoadEmojis={true}
        previewConfig={{showPreview: false}}
        height={370}
        autoFocusSearch={false}
        emojiStyle={EmojiStyle.NATIVE}
      />

```
Also when I try to access emoji in `handleEmojiClick` , some emojis are are appearing smaller without any color and empty rectangles

**Comment by ealush** [comment]
Unfortunately, this is just how windows renders them. I would recommend picking an alternative emojiStyle (non native) to show images instead of native OS emojis.
