### ISSUE TITLE
Is there any way to hide suggestion mode

### ISSUE THREAD

**Issue by hieunm22** [ealush/emoji-picker-react#423]
I found no way to hide suggestion mode in emoji picker
is it inside a setting or it hasn't been available?

![image](https://github.com/ealush/emoji-picker-react/assets/5255023/c977709d-63d2-4b7a-abe6-060db3e00140)

**Comment by jhonber** [comment]
Hello @hieunm22,
sure, you need to pass in `categories` prop an array with the list you want. In your case skip `Categories.SUGGESTED` category.

```js
const customCategories = [
  {
    category: Categories.SMILEYS_PEOPLE,
    name: 'Smileys & People',
  },
{
    category: Categories.ANIMALS_NATURE,
    name: 'Animals & Nature',
  },
  ...
];

<Picker
  categories={customCategories}
  ...
/>
```

**Comment by hieunm22** [comment]
thanks @jhonber
your idea is another solution that I can refer
I myself found my own solution which remove localStorage key "epr_suggested" everytime the emoji board is loaded then it works fine
Another solution for someone who needs to refer

**Comment by uigywnkiub** [comment]
> thanks [@jhonber](https://github.com/jhonber) your idea is another solution that I can refer I myself found my own solution which remove localStorage key "epr_suggested" everytime the emoji board is loaded then it works fine Another solution for someone who needs to refer

maybe this is not a solid solution?
