### ISSUE TITLE
Emoji Picker Throws Hydration Errors in Next JS

### ISSUE THREAD

**Issue by jimburch** [ealush/emoji-picker-react#444]
The picker renders and seems to work in my Next JS project, but throws a hydration error on render: `react-dom.development.js:6981 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error` (funny enough that link 404s)

Some steps I tried:
- One SO thread said to set the `emojiStyle` to NATIVE but this did not solve the issue
- Another thread on hydration errors said to wrap in different elements to see if anything changes, but it did not

Currently I have the picker on its own in the Home component, just to make sure something else wasn't throwing the error:
```jsx
export default function Home() {
  return (
    <div>
      <EmojiPicker />
    </div>
  )
}
```

**Comment by ealush** [comment]
My assumption is that it could be related to the recent emojis that don't get rendered in the server because they use local storage. Can you try erasing local storage and report back?

**Comment by jimburch** [comment]
Cleared local storage but the same errors persist. I did leave out this one if it provides any context: `react-dom.development.js:17594 Uncaught Error: There was an error while hydrating this Suspense boundary. Switched to client rendering.`
