### ISSUE TITLE
List react as a dependency

### ISSUE THREAD

**Issue by lukejacksonn** [ealush/emoji-picker-react#62]
I went to check the impact of adding this as a dependency to my app using bundlephobia. It reported that react was not listed as a dependency or peerDependency so could not complete the request.

![image](https://user-images.githubusercontent.com/1457604/38694349-4d8497f6-3e81-11e8-93d8-281b6fd1a565.png)

For something like this I would consider adding react as `peerDependency` is thing something you are willing to do? I am happy to make a PR if so.

**Comment by ealush** [comment]
I see your point here. Feel free to issue a PR. Thanks! 👍
