### ISSUE TITLE
issue when lunching app

### ISSUE THREAD

**Issue by ZeroCool00** [ealush/emoji-picker-react#65]
i just install this lib and run my project and i got this error

![screenshot_20180511-175609](https://user-images.githubusercontent.com/18139594/39924329-edb04340-5544-11e8-8ba2-7025dddf77e1.png)

**Comment by ealush** [comment]
Hey @ZeroCool00, thanks for taking interest in this project.

This is **not** a React-Native package, though. It only works with React-DOM applications. There is a variety of packages out there dedicated just for react native, but also, you should keep in mind that mobile phones already have an emoji keyboard built in (and maybe that's good enough for you).
