### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by imikemiller** [ealush/emoji-picker-react#93]
Some of the PNG from your set are not being served by the CDN:

EG: https://cdn.jsdelivr.net/emojione/assets/3.0/png/32/263a-fe0f.png

```<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>387806EF168052A6</RequestId>
<HostId>
SseLs5gyr8xkv/JthqB8cSmhEZfivql2D7MndRDMXHRQHgTL3UJhRlFVjCUnxvs1PEJmKp2RsSM=
</HostId>
</Error>

**Comment by ealush** [comment]
Hey @imikemiller, the problem you are facing due to the fact that I get the list of emojis from a different source than their images, so there may be mismatches. I'll try to find a way to self host the images, but that won't be immediate.

Sorry about that.
